config/routes.rb
Rails.application.routes.draw do
  get "/admin"=>"admin#index"

  get "/demo"=>"home#demo"
  get "/schedule"=>"home#schedule"
    
  resources :entries, except: [] do
    collection do
      get :export
    end
  end
  resources :players do
    collection { post :import }
  end

  namespace :admin do
    resources :entries
    resources :seasons
    resources :users, only: [:index, :destroy, :edit, :update]
    post :import_tournaments
  end

  devise_for :users
  root 'home#index'

  get '/:apple_touch_icon' => redirect('/favicon.ico'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

end

app/models/season.rb
class Season < ActiveRecord::Base
  has_many :entries
  has_many :players
  has_many :tournaments

  def self.active
    Season.where(active: true).first
  end

  def active=(value)
    Season.where("id != ?", id).update_all(active: false) if value
    write_attribute(:active, value)
  end
end

app/controllers/admin/seasons_controller.rb
class Admin::SeasonsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only
  before_filter :set_admin

  before_action :set_season, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index

    @seasons = Season.order(:id).all

  end

  def new
    @season = Season.new
    respond_with(@season)
  end

  def create
    @season = Season.new(season_params)
    @season.save!
    redirect_to admin_seasons_path
  end

  def edit
  end

  def update

    @season.update_attributes(season_params)
    redirect_to admin_seasons_path
  end

  def destroy
    @season.destroy
    redirect_to admin_seasons_path

  end

  private
    def set_season
      @season = Season.find(params[:id])
    end

    def season_params
      params.require(:season).permit(:name, :active, :rules, :allow_entries)
    end

    def set_admin
      @admin = true
    end
end

app/views/admin/seasons/edit.html.haml
%h3 Edit Season
.user-form
  = simple_form_for @season, url: admin_season_path(@season) do |f|
    = f.input :name
    = f.input :active
    = f.input :allow_entries
    = f.input :rules
    = f.button :submit

app/views/admin/seasons/index.html.haml
%h1 Seasons

%table.table.table-striped
  %tr
    %th ID
    %th Name
    %th Active
    %th

  - @seasons.each do |season|
    %tr
      %td=season.id
      %td=season.name
      %td=season.active
      %td
        = link_to 'Edit', edit_admin_season_path(season)
        = link_to 'Delete', admin_season_path(season), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Entry', new_admin_season_path, class: 'btn btn-primary'

app/views/admin/seasons/new.html.haml
%h3
  New Season
.user-form
  = simple_form_for @season, url: admin_seasons_path(@season) do |f|
    = f.input :name
    = f.input :active
    = f.input :allow_entries
    = f.input :rules
    = f.button :submit