config/routes.rb
Rails.application.routes.draw do
  get "/admin"=>"admin#index"

  get "/demo"=>"home#demo"
  get "/schedule"=>"home#schedule"
    
  resources :entries, except: [] do
    collection do
      get :export
    end
  end
  resources :players do
    collection { post :import }
  end

  namespace :admin do
    resources :entries
    resources :seasons
    resources :users, only: [:index, :destroy, :edit, :update]
    post :import_tournaments
  end

  devise_for :users
  root 'home#index'

  get '/:apple_touch_icon' => redirect('/favicon.ico'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :user
  belongs_to :player1, class_name: 'Player'
  belongs_to :player2, class_name: 'Player'
  belongs_to :player3, class_name: 'Player'
  belongs_to :player4, class_name: 'Player'
  belongs_to :player5, class_name: 'Player'
  belongs_to :player6, class_name: 'Player'
  belongs_to :player7, class_name: 'Player'
  belongs_to :player8, class_name: 'Player'
  belongs_to :season
  before_validation :set_season, on: :create
  validates_presence_of :season

  def total
    sum = 0
    (1..8).each do |i|
      sum = sum + send("player#{i}").salary if send("player#{i}")
    end
    sum
  end

  def players
    players = []
    (1..8).each do |i|
      players << send("player#{i}") if send("player#{i}")
    end

    players
  end

  def set_season
    self.season ||= Season.active
  end
end

app/controllers/admin/entries_controller.rb
class Admin::EntriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only
  before_filter :set_admin

  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    if params[:season].present?
      @entries = Season.find_by_name(params[:season]).entries.includes(:user)
    else
      @entries = Season.active.entries.includes(:user).all
    end
  end

  def show
    render 'entries/show'
  end

  def new
    @entry = Entry.new
    respond_with(@entry)
  end

  def edit
  end

  def update
    players = Array(params[:player_ids])
    players.each_with_index do |id, index|
      @entry.send("player#{index+1}_id=", id )
    end
    @entry.save
    respond_with(@entry)
  end

  def destroy
    @entry.destroy
    redirect_to admin_entries_path

  end

  private
    def set_entry
      @entry = Entry.find(params[:id])
    end

    def entry_params
      params[:entry]
    end

    def set_admin
      @admin = true
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :check_active, only: [:edit, :new, :create, :update]
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @entries = current_user.entries.all
    respond_with(@entries)
  end

  def show
    respond_with(@entry)
  end

  def new
    @entry = Entry.new
    respond_with(@entry)
  end

  def edit
    render :template => 'entries/new'
  end

  def create
    @entry = current_user.entries.build(entry_params)
    players = Array(params[:player_ids])
    players.each_with_index do |id, index|
      @entry.send("player#{index+1}_id=", id )
    end
    @entry.save
    respond_with(@entry)
  end

  def update
    players = Array(params[:player_ids])
    players.each_with_index do |id, index|
      @entry.send("player#{index+1}_id=", id )
    end
    @entry.save
    respond_with(@entry)
  end

  def destroy
    @entry.destroy
    respond_with(@entry)
  end

  def export
    @entries = Season.active.entries.all
    render xlsx: 'export'
  end

  private
    def set_entry
      @entry = current_user.entries.find(params[:id])
    end

    def entry_params
      params[:entry]
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_form.html.haml
= form_for @entry do |f|
  - if @entry.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entry.errors.count, "error")} prohibited this entry from being saved:"
      %ul
        - @entry.errors.full_messages.each do |msg|
          %li= msg

  .actions
    = f.submit 'Save'

app/views/entries/edit.html.haml
%h1 Editing entry

= render 'form'

= link_to 'Show', @entry
\|
= link_to 'Back', entries_path

app/views/entries/index.html.haml
%h1 Entries

%table.table.table-striped
  %tr
    %th Season
    %th ID
    %th Owner
    %th Email
    %th Players
    %th

  - @entries.each do |entry|
    %tr
      %td=entry.season.name
      %td=entry.id
      %td=entry.user.name
      %td=entry.user.email
      %td
        -entry.players.each do |player|
          ="#{player.name} | "
      %td
        = link_to 'Show', entry
        -if Season.active == entry.season
          = link_to 'Delete', entry, :method => :delete, :data => { :confirm => 'Are you sure?' }
          = link_to "Edit","/entries/#{entry.id}/edit#?id=#{entry.id}"

%br

= link_to 'New Entry', new_entry_path, class: 'btn btn-primary' unless @admin

app/views/entries/new.html.haml
.panel#ie-warning(style="display: none;" )
  .panel-body
    %h3(style="color: red;" ) Warning - You are using Internet Explorer.  IE is not supported, please use another browsers (Chrome, Firefox, Safari, etc.)
%h1 New Entry

.new-entry(ng-controller="NewEntry")
  %table.table.table-bordered.table-striped
    %tr(ng-repeat="pick in picks | orderBy:'salary'")
      %td
        {{pick.name}}
      %td
        {{pick.salary | currency:"$":0}}
      %td
        %a(ng-click="removePlayer(pick.id)")
          Remove
    %tr
      %td
        %b
          Total ({{picks.length}}/8):
      %td
        {{total() | currency:"$":0}}
        %span.label.label-danger(ng-show="total() > 7000000")
          Too much!
        %span
          | Remaining {{remaining() | currency:"$":0}}
  %form.form(ng-submit="createNew()")
    .row
      .col-md-4
        %ui-select(ng-model="selected_player.selected" theme="bootstrap" required)
          %ui-select-match(placeholder="Select Player") {{$select.selected.name}} {{$select.selected.salary | currency:"$":0}}
          %ui-select-choices(repeat="player.id as player in players | filter: $select.search")
            %div(ng-bind-html="player.name | highlight: $select.search")
            %small
              Salary: {{player.salary | currency:"$":0}}
      .col-md-8
        %a.btn.btn-primary(ng-click="addPlayer()" ng-disabled="!selected_player.selected")
          Add
        %span.label.label-danger(ng-show="error")
          {{error}}
    %br
    %button.btn.btn-primary(type="submit" ng-disabled="total() > 7000000 || picks.length != 8")
      Submit

= link_to 'Back', entries_path

app/views/entries/show.html.haml
.panel
  .panel-heading
    %h3
      Entry
      =@entry.id
    %h4
      Owner:
      =@entry.user.name
  .panel-body
    %table.table.table-bordered.table-striped
      %thead
        %tr
          %th Name
          %th Salary
      %tbody
        -(1..8).each do |i|
          -if @entry.send("player#{i}")
            %tr
              %td=@entry.send("player#{i}").name
              %td=number_to_currency(@entry.send("player#{i}").salary, precision: 0)
        %tr
          %td
            %b Total
          %td
            %b=number_to_currency(@entry.total, precision: 0)
= link_to 'Back', admin_entries_path