config/routes.rb
Rails.application.routes.draw do
  get "/admin"=>"admin#index"

  get "/demo"=>"home#demo"
  get "/schedule"=>"home#schedule"
    
  resources :entries, except: [] do
    collection do
      get :export
    end
  end
  resources :players do
    collection { post :import }
  end

  namespace :admin do
    resources :entries
    resources :seasons
    resources :users, only: [:index, :destroy, :edit, :update]
    post :import_tournaments
  end

  devise_for :users
  root 'home#index'

  get '/:apple_touch_icon' => redirect('/favicon.ico'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

end

app/models/player.rb
require 'csv'

class Player < ActiveRecord::Base

  before_validation :set_season, on: :create
  validates_presence_of :name, :salary, :season
  belongs_to :season


  def self.import(file)
    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      next if row['name'].blank?
      player = find_by_id(row["id"]) || new
      player.id = row['id'] unless player.persisted?
      player.name = row['name'].split.map(&:capitalize).join(' ')
      player.salary = row['salary']
      player.season = Season.active
      player.save!
    end
  end

  def self.open_spreadsheet(file)
    case File.extname(file.original_filename)
    when ".csv" then Roo::Csv.new(file.path, nil, :ignore)
    when ".xls" then Roo::Excel.new(file.path, nil, :ignore)
    when ".xlsx" then Roo::Excelx.new(file.path, nil, :ignore)
    else raise "Unknown file type: #{file.original_filename}"
    end
  end

  def set_season
    self.season ||= Season.active
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only, except: [:index]

  before_action :set_player, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @players = Season.active.players.order("salary desc")
    respond_with(@players)
  end

  def show
    respond_with(@player)
  end

  def new
    @player = Player.new
    respond_with(@player)
  end

  def edit
  end

  def create
    @player = Player.new(player_params)
    @player.save
    respond_with(@player)
  end

  def update
    @player.update(player_params)
    respond_with(@player)
  end

  def destroy
    @player.destroy
    respond_with(@player)
  end

  def import
    Player.import(params[:file])
    redirect_to players_path, notice: "Players imported."
  end

  private
    def set_player
      @player = Player.find(params[:id])
    end

    def player_params
      params[:player].permit(:name, :salary)
    end
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/players/_form.html.haml
= form_for @player do |f|
  - if @player.errors.any?
    #error_explanation
      %h2= "#{pluralize(@player.errors.count, "error")} prohibited this player from being saved:"
      %ul
        - @player.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :salary
    = f.text_field :salary
  .actions
    = f.submit 'Save'

app/views/players/edit.html.haml
%h1 Editing player

= render 'form'

= link_to 'Show', @player
\|
= link_to 'Back', players_path

app/views/players/index.html.haml
%h1 Players

=link_to "Download 2018 Salaries", asset_path('2018salaries.xlsx'), class: "btn btn-primary"
%br
%table.table.table-bordered.table-striped
  %tr
    %th ID
    %th Name
    %th Salary
    %th

  - @players.each do |player|
    %tr
      %td= player.id
      %td= player.name
      %td= number_to_currency player.salary, precision: 0
      %td
        -if current_user.admin?
          = link_to 'Edit', edit_player_path(player)
          = link_to 'Destroy', player, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

-if current_user.admin?
  = link_to 'New Player', new_player_path, class: 'btn btn-primary'

  %h2 Import Players
  =link_to "Example file", asset_path('salaries.xlsx')
  = form_tag import_players_path, multipart: true do
    = file_field_tag :file
    = submit_tag "Import", class: 'btn btn-primary', data: {disable_with: 'Importing...'}

app/views/players/new.html.haml
%h1 New player

= render 'form'

= link_to 'Back', players_path

app/views/players/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @player.name
%p
  %b Salary:
  = @player.salary

= link_to 'Edit', edit_player_path(@player)
\|
= link_to 'Back', players_path