config/routes.rb
Rails.application.routes.draw do
  get "/admin"=>"admin#index"

  get "/demo"=>"home#demo"
  get "/schedule"=>"home#schedule"
    
  resources :entries, except: [] do
    collection do
      get :export
    end
  end
  resources :players do
    collection { post :import }
  end

  namespace :admin do
    resources :entries
    resources :seasons
    resources :users, only: [:index, :destroy, :edit, :update]
    post :import_tournaments
  end

  devise_for :users
  root 'home#index'

  get '/:apple_touch_icon' => redirect('/favicon.ico'), constraints: { apple_touch_icon: /apple-touch-icon(-\d+x\d+)?(-precomposed)?\.png/ }

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :entries, dependent: :destroy
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :admin_only

  respond_to :html

  def index
    @users = User.all
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    redirect_to edit_admin_user_path(@user)
  end

  def edit
    @user = User.find(params[:id])
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end


  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/views/admin/users/edit.html.haml
%h3
  Edit
  =@user.name
.user-form
  = simple_form_for @user, url: admin_user_path(@user) do |f|
    = f.input :name, required: false
    = f.input :email
    = f.input :password
    = f.button :submit

app/views/admin/users/index.html.haml
%h1 Users

%table.table.table-striped
  %tr
    %th ID
    %th Name
    %th Entry Count
    %th
  -@users.each do |user|
    %tr
      %td=user.id
      %td=user.name
      %td=user.entries.count
      %td
        =link_to "Edit", edit_admin_user_path(user), class: 'btn btn-primary'
        |
        =link_to "Delete", admin_user_path(user), method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure?'}